services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: drug-indications-db
      POSTGRES_USER: drug-indications
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: