services:
  test-postgres-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: test-drug-indications-db
      POSTGRES_USER: test-drug-indications
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  test-postgres-data:

networks:
  test-network:
    name: drug-indications-test-network