services:
  app:
    container_name: drug-indications-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    environment:
      - GOOGLE_GEN_API_KEY=${GOOGLE_GEN_API_KEY}
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
